[project]
name = "techpubs-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ryan Tate", email = "ryan.tate@cirrusaircraft.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pgvector>=0.3.0",
    "psycopg[binary]>=3.0",
    "sqlalchemy[asyncio]>=2.0",
]

[project.optional-dependencies]
embeddings = [
    "openai>=1.12.0",
    "tenacity>=8.0",
    "azure-identity>=1.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
